### ISSUE TITLE
Put Beagle in a Container

### ISSUE THREAD

**Issue by thebigcorporation** [hihg-um/docker-java#1]
We can either add this to the Flare branch, since they play well together.
A different approach is to convert to a multi-stage build and put Beagle into a common base.
The latter would probably use close to the same amount of disk space, with the shared layers, but wouldn't burden a dedicated Flare or Beagle service with the redundant code.
At first glance, Beagle is not as friendly as Flare, the code doesn't come with much build infrastructure, INSTALL or BUILD instructions, and IIRC not even a README. Once that is sorted, maybe we can import into GitHub and try to push it back new and improved.

**Comment by kscott-1** [comment]
Currently exists on main, closing as completed
